"""Adding blog pic path

Revision ID: 06e8e71a9cba
Revises: b6ab5559ae90
Create Date: 2018-05-27 02:47:55.275716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e8e71a9cba'
down_revision = 'b6ab5559ae90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_pic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog_pic')
    # ### end Alembic commands ###
