"""Removing photos column from the blogs table

Revision ID: 7616c84128a1
Revises: 8facb60d080b
Create Date: 2018-05-26 10:21:00.445331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7616c84128a1'
down_revision = '8facb60d080b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
