"""Adding email to the comments section

Revision ID: 8facb60d080b
Revises: 37b5122989b1
Create Date: 2018-05-25 19:59:22.608248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8facb60d080b'
down_revision = '37b5122989b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'email')
    # ### end Alembic commands ###
